# Site settings
title: an enlightened state of brass
header-img: img/home-bg.png
email: bm.clarkson@gmail.com
copyright_name: bmclarkson
description: > # this means to ignore newlines until "baseurl:"
  documenting life change
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bmclarkson
learn_profile: bmclarkson
email_username: bm.clarkson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
